# base layout
<BaseLayout>:
    orientation: "vertical"
    size: root.width, root.height

# board layout
<BoardButton>:
    # background
    background_normal: ""
    background_color: (0, 0, 0, 0)

    # size
    size_hint: (None, None)
    size: (75, 75)

    # border
    canvas.before:
        Color:
            rgba: (0, 0, 0, 1)
        Line:
            width: 2
            rectangle: self.x, self.y, self.width, self.height